### ISSUE TITLE
Resources labs

### ISSUE THREAD

**Issue by hackty** [hackty/SEBC#4]

**Comment by hackty** [comment]
complete 1_YarnCalcs.png

**Comment by hackty** [comment]
complete 2_service_usage.png

**Comment by hackty** [comment]
complete 3_YARNtest.sh.md and 4_YARN_results.md

**Comment by hackty** [comment]
complete 5_YARN_Charts.png

**Comment by mfernest** [comment]
I was hoping `3_YARNtest.sh.md` would reflect the values you used in your performance tests.
