### ISSUE TITLE
Security labs

### ISSUE THREAD

**Issue by hackty** [hackty/SEBC#6]

**Comment by hackty** [comment]
complete krb5.conf.md

**Comment by hackty** [comment]
complete kdc.conf.md

**Comment by hackty** [comment]
complete kadm5.acl.md

**Comment by hackty** [comment]
complete kinit.md

**Comment by hackty** [comment]
complete sentry-test.md

**Comment by mfernest** [comment]
Thorough documentation of your process should become a useful reference.
